# Generated by Django 2.2.3 on 2019-11-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191108_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantmodel',
            name='contact',
            field=models.IntegerField(max_length=30, unique=True),
        ),
    ]
