# Generated by Django 2.2.3 on 2019-11-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191108_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantmodel',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
