# Generated by Django 2.2.3 on 2019-11-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191108_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantmodel',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
