# Generated by Django 2.2.3 on 2019-11-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191108_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantmodel',
            name='contact',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
