# Generated by Django 2.2.3 on 2019-11-10 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191108_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('p_no', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50, unique=True)),
                ('p_price', models.FloatField()),
                ('p_qunt', models.IntegerField()),
                ('p_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.merchantModel')),
            ],
        ),
    ]
